# Generated by Django 5.2.3 on 2025-06-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=30, unique=True)),
                ('weight_per_bag', models.DecimalField(decimal_places=2, help_text='Weight in kilograms per bag', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PermitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(editable=False, max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_start', models.DateField(blank=True, null=True)),
                ('delivery_end', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated revenue based on coffee prices at the time of application', max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_quantity', models.PositiveIntegerField()),
                ('coffee_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_quantities', to='permits.coffeegrade')),
            ],
            options={
                'verbose_name_plural': 'Coffee Quantities',
            },
        ),
    ]
