# Generated by Django 5.2.3 on 2025-06-17 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits', '0001_initial'),
        ('societies', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_permits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='societies.factory'),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_permits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='societies.society'),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='coffeequantity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coffee_quantities', to='permits.permitapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='coffeequantity',
            unique_together={('application', 'coffee_grade')},
        ),
    ]
