# Generated by Django 5.2.3 on 2025-06-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitapplication',
            name='estimated_revenue',
        ),
    ]
