# Generated by Django 5.2.3 on 2025-06-24 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_remove_permitapplication_estimated_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeegrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeegrade',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coffeegrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
