# Generated by Django 5.2.3 on 2025-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_coffeegrade_created_at_coffeegrade_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='ref_no',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
