# Generated by Django 5.2.3 on 2025-08-04 00:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_alter_permitapplication_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('max_verifications', models.PositiveIntegerField(default=1000)),
                ('access_level', models.CharField(choices=[('DOWNLOAD', 'Download PDF'), ('VIEW_ONLY', 'View Only')], default='VIEW_ONLY', max_length=10)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='permits.permitapplication')),
            ],
            options={
                'verbose_name': 'Permit QR Code',
                'verbose_name_plural': 'Permit QR Codes',
            },
        ),
        migrations.CreateModel(
            name='QRCodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('DOWNLOAD', 'Download PDF'), ('VIEW_ONLY', 'View Only')], default='VIEW_ONLY', max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.permitqrcode')),
            ],
            options={
                'verbose_name': 'QR Code Verification',
                'verbose_name_plural': 'QR Code Verifications',
                'indexes': [models.Index(fields=['verified_at'], name='permits_qrc_verifie_36170f_idx'), models.Index(fields=['ip_address'], name='permits_qrc_ip_addr_636074_idx'), models.Index(fields=['access_level'], name='permits_qrc_access__980c12_idx')],
            },
        ),
    ]
