# Generated by Django 5.2.3 on 2025-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Frequency of summary/digest emails', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_permit_expiry',
            field=models.BooleanField(default=True, help_text='Receive email reminders for permit expiry'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_permit_status',
            field=models.BooleanField(default=True, help_text='Receive email notifications for permit status changes'),
        ),
    ]
