# Generated by Django 5.2.3 on 2025-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('details', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CoffeePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_year', models.CharField(help_text='Coffee year in format YYYY/YY', max_length=9, verbose_name='coffee year')),
                ('price_per_bag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per bag')),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_set', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-coffee_year', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='factory name')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='society name')),
                ('county', models.CharField(max_length=100, verbose_name='county')),
                ('sub_county', models.CharField(max_length=100, verbose_name='sub county')),
                ('is_approved', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='rejection reason')),
                ('date_rejected', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
