# Generated by Django 5.2.3 on 2025-06-17 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits', '0002_initial'),
        ('societies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coffeeprice',
            name='coffee_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='permits.coffeegrade', verbose_name='coffee grade'),
        ),
        migrations.AddField(
            model_name='society',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='society',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='managed_society', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='society',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factory',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='societies.society'),
        ),
        migrations.AddField(
            model_name='coffeeprice',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_prices', to='societies.society'),
        ),
        migrations.AlterUniqueTogether(
            name='coffeeprice',
            unique_together={('society', 'coffee_grade', 'coffee_year')},
        ),
    ]
