# Generated by Django 5.2.3 on 2025-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_remove_factory_location_factory_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='society name'),
        ),
    ]
