# Generated by Django 5.2.3 on 2025-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0004_alter_society_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='cancel_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='society',
            name='cancel_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
